### ISSUE TITLE
Error in initialization

### ISSUE THREAD

**Issue by alparp27** [mapbox/mapbox-search-android-examples#27]
More info from firebase:
<img width="844" alt="Screen Shot 2021-05-21 at 11 57 56 AM" src="https://user-images.githubusercontent.com/30812939/119185657-d5e75600-ba2b-11eb-8178-3da5d3c1bf24.png">

Stack trace:
Fatal Exception: java.lang.RuntimeException: Unable to create application com.everlance.EverlanceApplication: java.lang.IllegalStateException: Maximum limit of concurrent alarms 500 reached for uid: u0a584, callingPackage: com.everlance
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7625)
       at android.app.ActivityThread.access$1800(ActivityThread.java:272)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2103)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:262)
       at android.app.ActivityThread.main(ActivityThread.java:8665)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

Steps to reproduce: unknown/hard to reproduce

**Comment by DzmitryFomchyn** [comment]
@alparp27 Search SDK doesn't use Alarm functionality (I'm not aware of our internal dependencies, I'll check that).
Are you sure that this crash is connected to the Search SDK?

**Comment by friendoye** [comment]
@alparp27 could you, please, recheck that provided stack trace isn't truncated? It looks like some stack traces are missing, especially here:
```
Fatal Exception: java.lang.RuntimeException: Unable to create application com.everlance.EverlanceApplication: java.lang.IllegalStateException: Maximum limit of concurrent alarms 500 reached for uid: u0a584, callingPackage: com.everlance
// <-- Missing entries 🤔 
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7625)
...
```

**Comment by DzmitryFomchyn** [comment]
@alparp27 the issue might be in our internal SDK. Feel free to add more details https://github.com/mapbox/mapbox-events-android/issues/533

Also, it'd be helpful if you could share full firebase report (make sure it doesn't contain any NDA)

**Comment by DzmitryFomchyn** [comment]
Closing this issue in favor of mapbox/mapbox-events-android#533
