### ISSUE TITLE
Demo app crash

### ISSUE THREAD

**Issue by KayHung** [mapbox/mapbox-search-android-examples#29]
Demo app crash
```
Process: com.mapbox.search.demo, PID: 29015
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mapbox.search.demo/com.mapbox.search.demo.api.CategorySearchJavaExampleActivity}: java.lang.NullPointerException: imm.currentInputMethodSubtype must not be null
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3543)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3688)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2255)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:230)
        at android.app.ActivityThread.main(ActivityThread.java:7834)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

test device: vivo nex3
search demo version : mapbox-search-android-examples-1.0.0-beta.8

**Comment by friendoye** [comment]
@KayHung 👋 

Could you check if this crash happens on the latest version of Search Demo App, please?

**Comment by DzmitryFomchyn** [comment]
@KayHung This crash has been fixed in https://github.com/mapbox/mapbox-search-android/releases/tag/v1.0.0-beta.9, please check that version.

Looking forward to your feedback!

**Comment by KayHung** [comment]
I try the latest version, this issue has been fixed.
