### ISSUE TITLE
Search SDK returns error when device languages is different than English (ex: French)

### ISSUE THREAD

**Issue by zicyApp** [mapbox/mapbox-search-android-examples#41]
## Environment

- Android OS version: Any
- Devices affected: Any
- Search SDK Version: 1.0.0-beta.18

## Code examples

`private lateinit var searchEngine: SearchEngine`
`private lateinit var searchRequestTask: SearchRequestTask`

`searchRequestTask = searchEngine.search(`
      `searchText ?: "",`
      `SearchOptions(`
          `limit = 5,`
          `countries = listOf(Country.CANADA, Country.UNITED_STATES),`
          `languages = listOf(Language.ENGLISH, Language.FRENCH)`
      `),`
      `searchCallback`
 `)`

## Observed behavior and steps

1. Entering "montreal" into input field
2. SDK returns ERROR with the following exception

3. Exception: 
2021-08-30 08:45:21.260 8241-8241/com.xxx.zzz E/SearchSDK: Error!
    java.lang.IllegalArgumentException: Unexpected char 0xe9 at 8 in User-Agent value: App/3.5.280 (com.xxx.zzz; build:35280; Android 10) MapboxSearchSDK-Android/1.0.0-beta.18
        at okhttp3.Headers$Companion.checkValue(Headers.kt:434)
        at okhttp3.Headers$Companion.access$checkValue(Headers.kt:346)
        at okhttp3.Headers$Builder.add(Headers.kt:245)
        at okhttp3.Request$Builder.addHeader(Request.kt:210)
        at com.mapbox.search.core.http.HttpClientImpl.makeRequest(HttpClientImpl.kt:36)
        at com.mapbox.search.core.http.HttpClientImpl.httpGet(HttpClientImpl.kt:23)
        at com.mapbox.search.core.PlatformClientImpl.httpRequest(PlatformClientImpl.kt:20)
        at com.mapbox.search.internal.bindgen.SearchEngine.search(Native Method)
        at com.mapbox.search.SearchEngineImpl$search$1.invoke(SearchEngine.kt:204)
        at com.mapbox.search.SearchEngineImpl$search$1.invoke(SearchEngine.kt:189)
        at com.mapbox.search.engine.BaseSearchEngine.makeRequest(BaseSearchEngine.kt:13)
        at com.mapbox.search.SearchEngineImpl.search(SearchEngine.kt:202)
        at com.eptix.app.ui.sites.search.SearchFragment.runnable$lambda-0(SearchFragment.kt:81)
        at com.eptix.app.ui.sites.search.SearchFragment.$r8$lambda$oW0luY84jOwGfzsc55rYf7covuU(Unknown Source:0)
        at com.eptix.app.ui.sites.search.SearchFragment$$ExternalSyntheticLambda4.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7557)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:937)
2021-08-30 08:45:21.265 8241-8241/com.xxx.zzz E/ErrorUtils: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 1 column 982 path $.customData

## Expected behavior

- Request should return a list of results.
- Exception does not occur when the phone language is set to english

**Comment by friendoye** [comment]
Hey, @zicyApp, thanks for reporting this!

I was able to find root cause of this error and we will fix it in one of the nearest releases.

**Comment by DzmitryFomchyn** [comment]
This issue has been fixed in the Search SDK [v1.0.0-beta.19](https://github.com/mapbox/mapbox-search-android-examples/releases/tag/v1.0.0-beta.19).

@zicyApp fee free to reopen this issue or create a new one if a similar bug still happens.
